version: '3'
services:
  pe-nginx:
   container_name: pe-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app

  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    expose:
      - 8080
    ports:
      - 8080:8080
    command: bash -c "mvn spring-boot:run"